/** @format */

export const designTypes = [
	{
		id: 1,
		image: "/portfolio/main/bloc-main.jpg",
		alt: "Instagram ad for Block Aero an aviation company",
		link: "/graphics",
		text: "Graphic Design",
		usesModal: false,
	},
	{
		id: 2,
		image: "/portfolio/main/vines.jpg",
		alt: "Butterfly illustration",
		link: "/illustration",
		text: "Illustration",
		usesModal: false,
	},
	{
		id: 3,
		image: "/portfolio/main/butterfly-main.jpg",
		alt: "Artstore art project",
		link: "/development",
		text: "Development",
		usesModal: false,
	},
];

export const graphics = [
	{
		id: 1,
		image: "/portfolio/main/bloc-main.jpg",
		alt: "Instagram ad for Block Aero an aviation company",
		link: "/block",
		text: "Block Aero Technologies",
		usesModal: false,
		threeOnLargeScreen: true,
	},
	{
		id: 2,
		image: "/portfolio/main/cr-main.jpg",
		alt: "Baby shower book",
		link: "/gibson",
		text: "C.R Gibson",
		usesModal: false,
	},
	{
		id: 3,
		image: "/portfolio/main/clever.jpg",
		alt: "Clever Factory gift bag",
		link: "/clever",
		text: "The Clever Factory",
		usesModal: false,
	},
	{
		id: 4,
		image: "/portfolio/main/jjill-main.png",
		alt: "J.Jill",
		link: "/jjill",
		text: "J.Jill",
		usesModal: false,
	},
	{
		id: 5,
		image: "/portfolio/main/w-main.jpg",
		alt: "Wildkin instagram",
		link: "/wildkin",
		text: "Wildkin",
		usesModal: false,
	},
	{
		id: 6,
		image: "/portfolio/cr/witch_book.jpg",
		alt: "Freelance book",
		link: "/freelance",
		text: "Freelance Projects",
		usesModal: false,
	},
];

// Different graphic projects based on customer

export const block = [
	{
		id: 1,
		image: "/portfolio/block/print/flier-1.jpg",
		alt: "Instagram ad for Block Aero an aviation company",
		link: "/block",
		text: "Flyer created for Singapore Airshow",
		usesModal: true,
		threeOnLargeScreen: false,
	},
	{
		id: 1,
		image: "/portfolio/block/print/flier-2.jpg",
		alt: "Instagram ad for Block Aero an aviation company",
		link: "/block",
		text: "Flyer created for China Parts Airshow",
		usesModal: true,
		threeOnLargeScreen: false,
	},
];

export const blockDigital = [
	{
		id: 1,
		image: "/portfolio/block/instagram_congrats.jpg",
		alt: "Instagram ad for Block Aero an aviation company",
		link: "/block",
		text: "Flyer created for Singapore Airshow",
		usesModal: true,
		threeOnLargeScreen: true,
	},
	{
		id: 1,
		image: "/portfolio/block/instagram.jpg",
		alt: "Instagram ad for Block Aero an aviation company",
		link: "/block",
		text: "Flyer created for China Parts Airshow",
		usesModal: true,
		threeOnLargeScreen: true,
	},
	{
		id: 1,
		image: "/portfolio/block/linkedIn.jpg",
		alt: "LinkedIn ad for Block Aero an aviation company",
		link: "/block",
		text: "LinkedIn post",
		usesModal: true,
		threeOnLargeScreen: true,
	},
];

// All Illustrations

export const illustrations = [
	{
		alt: "sky",
		link: "",
		image: "/portfolio/art/sky.png",
		text: "Night Sky",
		usesModal: true,
		threeOnLargeScreen: true,
	},
	{
		alt: "Notebook with butterfly illustration",
		link: "",
		image: "/portfolio/art/vines.jpg",
		text: "Butterfly",
		usesModal: true,
		threeOnLargeScreen: true,
	},
	{
		alt: "Curled up fox",
		link: "",
		image: "/portfolio/art/fox.jpg",
		text: "Fox Curled",
		usesModal: true,
		threeOnLargeScreen: true,
	},
	{
		alt: "Illustration of cactus",
		link: "",
		image: "/portfolio/art/cactus.jpg",
		text: "Fox Curled",
		usesModal: true,
		threeOnLargeScreen: true,
	},
	{
		alt: "Illustration of cities",
		link: "",
		image: "/portfolio/art/cities.jpg",
		text: "Mykonos",
		usesModal: true,
		threeOnLargeScreen: true,
	},
	{
		alt: "Illustration of divbars",
		link: "",
		image: "/portfolio/art/div_bar.jpg",
		text: "Dive Bar",
		usesModal: true,
		threeOnLargeScreen: true,
	},
	{
		alt: "Illustration of palm trees",
		link: "",
		image: "/portfolio/art/palm_print.jpg",
		text: "Mykonos",
		usesModal: true,
		threeOnLargeScreen: true,
	},
	{
		alt: "Illustration of woman",
		link: "",
		image: "/portfolio/art/blue_lady.jpg",
		text: "Mykonos",
		usesModal: true,
		threeOnLargeScreen: true,
	},
	{
		alt: "Illustration of woman",
		link: "",
		image: "/portfolio/art/purple_lady.jpg",
		text: "Mykonos",
		usesModal: true,
		threeOnLargeScreen: true,
	},
	{
		alt: "Illustration of snake",
		link: "",
		image: "/portfolio/art/snake.jpg",
		text: "Mykonos",
		usesModal: true,
		threeOnLargeScreen: true,
	},
	{
		alt: "Illustration of mushroom",
		link: "",
		image: "/portfolio/art/mushroom.jpg",
		text: "Mykonos",
		usesModal: true,
		threeOnLargeScreen: true,
	},
	{
		alt: "Illustration of hedgehog",
		link: "",
		image: "/portfolio/art/hedgehog.jpg",
		text: "Mykonos",
		usesModal: true,
	},
	{
		alt: "Illustration of bear",
		link: "",
		image: "/portfolio/art/bear.jpg",
		text: "Mykonos",
		usesModal: true,
		threeOnLargeScreen: true,
	},
	{
		alt: "Illustration of fox",
		link: "",
		image: "/portfolio/art/Fox2.jpg",
		text: "Mykonos",
		usesModal: true,
		threeOnLargeScreen: true,
	},
	{
		alt: "Illustration of deer",
		link: "",
		image: "/portfolio/art/deer.jpg",
		text: "Mykonos",
		usesModal: true,
		threeOnLargeScreen: true,
	},
	{
		alt: "Illustration of butterfly",
		link: "",
		image: "/portfolio/art/butterfly.jpg",
		text: "Mykonos",
		usesModal: true,
		threeOnLargeScreen: true,
	},
];
